a = input('Digite algo:')
print('O tipo primitivo desse valor é',type(a))
print('É um numero?:', a.isnumeric())
print('É alfabetico?:', a.isalpha())
print('É alfanumerico?:', a.isalnum())
print('É tudo maiuscula?:', a.isupper())
